# Generated by Django 4.2.20 on 2025-04-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cmtserver", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="customuser", options={},),
    ]
