# Generated by Django 4.2.20 on 2025-04-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cmtserver", "0003_alter_customuser_grade_alter_login_username_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="login", table="login",),
    ]
