# Generated by Django 4.2.20 on 2025-04-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cmtserver", "0004_alter_login_table"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="username",),
    ]
