# Generated by Django 4.2.20 on 2025-04-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmtserver", "0005_remove_customuser_username"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
        migrations.RemoveField(model_name="customuser", name="date_joined",),
        migrations.RemoveField(model_name="customuser", name="groups",),
        migrations.RemoveField(model_name="customuser", name="is_active",),
        migrations.RemoveField(model_name="customuser", name="is_staff",),
        migrations.RemoveField(model_name="customuser", name="is_superuser",),
        migrations.RemoveField(model_name="customuser", name="user_permissions",),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
