# Generated by Django 4.2.20 on 2025-04-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmtserver", "0007_alter_customuser_managers_customuser_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
        migrations.RemoveField(model_name="customuser", name="date_joined",),
        migrations.RemoveField(model_name="customuser", name="first_name",),
        migrations.RemoveField(model_name="customuser", name="groups",),
        migrations.RemoveField(model_name="customuser", name="is_staff",),
        migrations.RemoveField(model_name="customuser", name="is_superuser",),
        migrations.RemoveField(model_name="customuser", name="last_name",),
        migrations.RemoveField(model_name="customuser", name="user_permissions",),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
