# Generated by Django 4.2.20 on 2025-04-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmtserver", "0008_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
