# Generated by Django 4.2.20 on 2025-04-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cmtserver", "0009_customuser_first_name_customuser_last_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="last_login",),
    ]
